const mlbGamesTestData = [
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288400-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_oakmlb_nyamlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288400-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288400-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_oakmlb_nyamlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_oakmlb_nyamlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_oakmlb_nyamlb_1&mode=preview&c_id=mlb',
      tv_station: 'YES',
    },
    broadcast: {
      home: { tv: 'YES', radio: 'WCBS 880, WADO 1280' },
      away: { tv: 'NBCSCA', radio: '95.7 FM The Game' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Bottom',
      note: '',
      reason: '',
      inning: '9',
      balls: '1',
      strikes: '1',
      outs: '3',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '425545',
          last: 'Willingham',
          first: 'Josh',
          name_display_roster: 'Willingham',
          number: '16',
          hr: '1',
          std_hr: '13',
          inning: '3',
          runners: '1',
          team_code: 'oak',
        },
        {
          id: '430897',
          last: 'Swisher',
          first: 'Nick',
          name_display_roster: 'Swisher',
          number: '33',
          hr: '1',
          std_hr: '12',
          inning: '6',
          runners: '0',
          team_code: 'nya',
        },
        {
          id: '425686',
          last: 'Matsui',
          first: 'Hideki',
          name_display_roster: 'Matsui',
          number: '55',
          hr: '1',
          std_hr: '8',
          inning: '7',
          runners: '0',
          team_code: 'oak',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '2' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '1' },
        { home: '0', away: '1' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
      ],
      r: { home: '3', away: '4', diff: '1' },
      h: { home: '9', away: '10' },
      e: { home: '0', away: '0' },
      hr: { home: '1', away: '2' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Rich',
      id: '425848',
      last: 'Harden',
      name_display_roster: 'Harden',
      number: '18',
      wins: '2',
      losses: '1',
      era: '4.63',
    },
    losing_pitcher: {
      first: 'A.J.',
      id: '150359',
      last: 'Burnett',
      name_display_roster: 'Burnett',
      number: '34',
      wins: '8',
      losses: '8',
      era: '4.21',
    },
    save_pitcher: {
      first: 'Andrew',
      id: '457732',
      last: 'Bailey',
      name_display_roster: 'Bailey',
      number: '40',
      wins: '0',
      losses: '2',
      era: '2.37',
      saves: '11',
      svo: '13',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/oaknya_288400_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/oaknya_288400_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/oaknya_288400_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288400-2011-07-23',
        start: '2011-07-23T17:05:00Z',
        title: 'OAK @ NYY',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/oaknya_288400_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_archive',
      },
    },
    id: '2011/07/23/oakmlb-nyamlb-1',
    game_pk: '288400',
    venue: 'Yankee Stadium',
    original_date: '2011/07/23',
    resume_date: '',
    time: '1:05',
    time_date: '2011/07/23 1:05',
    time_date_aw_lg: '2011/07/23 1:05',
    time_date_hm_lg: '2011/07/23 1:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '10:05',
    away_time_zone: 'PT',
    away_ampm: 'AM',
    home_time: '1:05',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '1:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '1:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '3313',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'NYY',
    home_code: 'nya',
    home_file_code: 'nyy',
    home_team_id: '147',
    home_team_city: 'NY Yankees',
    home_team_name: 'Yankees',
    home_division: 'E',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'OAK',
    away_code: 'oak',
    away_file_code: 'oak',
    away_team_id: '133',
    away_team_city: 'Oakland',
    away_team_name: 'Athletics',
    away_division: 'W',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USNY0172',
    location: 'Bronx, NY',
    gameday: '2011_07_23_oakmlb_nyamlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '44',
    away_loss: '56',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '58',
    home_loss: '40',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_oakmlb_nyamlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288397-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_houmlb_chnmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288397-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288397-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_houmlb_chnmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_houmlb_chnmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_houmlb_chnmlb_1&mode=preview&c_id=mlb',
      tv_station: 'NBCSP',
    },
    broadcast: {
      home: { tv: 'NBCSP', radio: 'WGN 720' },
      away: {
        tv: 'FS-H HD, DirecTV-678, Dish444, DishHD-9514',
        radio: 'KTRH 740 AM/99.1 FM HD-2, KLAT 1010',
      },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '1',
      strikes: '2',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '407781',
          last: 'Byrd',
          first: 'Marlon',
          name_display_roster: 'Byrd',
          number: '24',
          hr: '1',
          std_hr: '5',
          inning: '2',
          runners: '0',
          team_code: 'chn',
        },
        {
          id: '434567',
          last: 'Soto',
          first: 'Geovany',
          name_display_roster: 'Soto',
          number: '18',
          hr: '1',
          std_hr: '9',
          inning: '5',
          runners: '0',
          team_code: 'chn',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '1' },
        { home: '0', away: '0' },
        { home: '3', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '5', away: '1', diff: '4' },
      h: { home: '6', away: '9' },
      e: { home: '0', away: '2' },
      hr: { home: '3', away: '2' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Randy',
      id: '448694',
      last: 'Wells',
      name_display_roster: 'Wells',
      number: '36',
      wins: '2',
      losses: '3',
      era: '6.17',
    },
    losing_pitcher: {
      first: 'Wandy',
      id: '434643',
      last: 'Rodriguez',
      name_display_roster: 'Rodriguez',
      number: '51',
      wins: '6',
      losses: '7',
      era: '3.60',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/houchn_288397_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/houchn_288397_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/houchn_288397_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288397-2011-07-23',
        start: '2011-07-23T17:05:00Z',
        title: 'HOU @ CHC',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/houchn_288397_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_archive',
      },
    },
    id: '2011/07/23/houmlb-chnmlb-1',
    game_pk: '288397',
    venue: 'Wrigley Field',
    original_date: '2011/07/23',
    resume_date: '',
    time: '1:05',
    time_date: '2011/07/23 1:05',
    time_date_aw_lg: '2011/07/23 1:05',
    time_date_hm_lg: '2011/07/23 1:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '12:05',
    away_time_zone: 'CT',
    away_ampm: 'PM',
    home_time: '12:05',
    home_time_zone: 'CT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '1:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '1:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '17',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '34',
    series_num: '34',
    ser_games: '3',
    home_name_abbrev: 'CHC',
    home_code: 'chn',
    home_file_code: 'chc',
    home_team_id: '112',
    home_team_city: 'Chi Cubs',
    home_team_name: 'Cubs',
    home_division: 'C',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'HOU',
    away_code: 'hou',
    away_file_code: 'hou',
    away_team_id: '117',
    away_team_city: 'Houston',
    away_team_name: 'Astros',
    away_division: 'C',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USIL0225',
    location: 'Chicago, IL',
    gameday: '2011_07_23_houmlb_chnmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '33',
    away_loss: '67',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '41',
    home_loss: '60',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_houmlb_chnmlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288401-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_sdnmlb_phimlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288401-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288401-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_sdnmlb_phimlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_sdnmlb_phimlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_sdnmlb_phimlb_1&mode=preview&c_id=mlb',
      tv_station: 'FOX',
    },
    broadcast: {
      home: { tv: 'FOX', radio: '1210 WPHT, WUBA 1480' },
      away: { tv: 'FOX', radio: 'XPRS 1090, XEMO 860' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '1',
      strikes: '3',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '457727',
          last: 'Maybin',
          first: 'Cameron',
          name_display_roster: 'Maybin',
          number: '24',
          hr: '2',
          std_hr: '6',
          inning: '6',
          runners: '1',
          team_code: 'sdn',
        },
        {
          id: '452104',
          last: 'Headley',
          first: 'Chase',
          name_display_roster: 'Headley',
          number: '7',
          hr: '2',
          std_hr: '3',
          inning: '6',
          runners: '0',
          team_code: 'sdn',
        },
        {
          id: '429667',
          last: 'Howard',
          first: 'Ryan',
          name_display_roster: 'Howard',
          number: '6',
          hr: '2',
          std_hr: '19',
          inning: '7',
          runners: '0',
          team_code: 'phi',
        },
        {
          id: '492841',
          last: 'Martinez',
          first: 'Michael',
          name_display_roster: 'Martinez',
          number: '7',
          hr: '2',
          std_hr: '2',
          inning: '7',
          runners: '2',
          team_code: 'phi',
        },
        {
          id: '400284',
          last: 'Utley',
          first: 'Chase',
          name_display_roster: 'Utley',
          number: '26',
          hr: '2',
          std_hr: '6',
          inning: '7',
          runners: '0',
          team_code: 'phi',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '3', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '3' },
        { home: '5', away: '1' },
        { home: '0', away: '2' },
        { home: '', away: '0' },
      ],
      r: { home: '8', away: '6', diff: '2' },
      h: { home: '11', away: '11' },
      e: { home: '0', away: '0' },
      hr: { home: '7', away: '4' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Michael',
      id: '452741',
      last: 'Stutes',
      name_display_roster: 'Stutes',
      number: '40',
      wins: '5',
      losses: '1',
      era: '3.38',
    },
    losing_pitcher: {
      first: 'Chad',
      id: '430589',
      last: 'Qualls',
      name_display_roster: 'Qualls',
      number: '50',
      wins: '4',
      losses: '5',
      era: '3.51',
    },
    save_pitcher: {
      first: 'Ryan',
      id: '425492',
      last: 'Madson',
      name_display_roster: 'Madson',
      number: '46',
      wins: '3',
      losses: '1',
      era: '2.02',
      saves: '17',
      svo: '18',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/sdnphi_288401_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/sdnphi_288401_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/sdnphi_288401_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: { type: 'game', calendar_event_id: '14-288401-2011-07-23' },
    },
    id: '2011/07/23/sdnmlb-phimlb-1',
    game_pk: '288401',
    venue: 'Citizens Bank Park',
    original_date: '2011/07/23',
    resume_date: '',
    time: '4:10',
    time_date: '2011/07/23 4:10',
    time_date_aw_lg: '2011/07/23 4:10',
    time_date_hm_lg: '2011/07/23 4:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '1:10',
    away_time_zone: 'PT',
    away_ampm: 'PM',
    home_time: '4:10',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '4:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '4:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '2681',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '4',
    home_name_abbrev: 'PHI',
    home_code: 'phi',
    home_file_code: 'phi',
    home_team_id: '143',
    home_team_city: 'Philadelphia',
    home_team_name: 'Phillies',
    home_division: 'E',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'SD',
    away_code: 'sdn',
    away_file_code: 'sd',
    away_team_id: '135',
    away_team_city: 'San Diego',
    away_team_name: 'Padres',
    away_division: 'W',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USPA1276',
    location: 'Philadelphia, PA',
    gameday: '2011_07_23_sdnmlb_phimlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '44',
    away_loss: '57',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '63',
    home_loss: '36',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_sdnmlb_phimlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288396-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_detmlb_minmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288396-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288396-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_detmlb_minmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_detmlb_minmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_detmlb_minmlb_1&mode=preview&c_id=mlb',
      tv_station: 'FOX',
    },
    broadcast: {
      home: { tv: 'FOX', radio: 'TIBN' },
      away: { tv: 'FOX', radio: 'WXYT 97.1 FM' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '1',
      strikes: '0',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: {
        id: '502143',
        last: 'Valencia',
        first: 'Danny',
        name_display_roster: 'Valencia',
        number: '22',
        hr: '1',
        std_hr: '12',
        inning: '2',
        runners: '0',
        team_code: 'min',
      },
    },
    linescore: {
      inning: [
        { home: '1', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '0' },
        { home: '2', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '1' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '4', away: '1', diff: '3' },
      h: { home: '7', away: '8' },
      e: { home: '0', away: '1' },
      hr: { home: '8', away: '4' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Scott',
      id: '435044',
      last: 'Baker',
      name_display_roster: 'Baker',
      number: '30',
      wins: '8',
      losses: '5',
      era: '2.88',
    },
    losing_pitcher: {
      first: 'Brad',
      id: '207267',
      last: 'Penny',
      name_display_roster: 'Penny',
      number: '31',
      wins: '7',
      losses: '7',
      era: '4.51',
    },
    save_pitcher: {
      first: 'Joe',
      id: '150274',
      last: 'Nathan',
      name_display_roster: 'Nathan',
      number: '36',
      wins: '1',
      losses: '1',
      era: '5.06',
      saves: '7',
      svo: '10',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/detmin_288396_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/detmin_288396_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/detmin_288396_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288396-2011-07-23',
        start: '2011-07-23T20:10:00Z',
        title: 'DET @ MIN',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/detmin_288396_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/detmlb-minmlb-1',
    game_pk: '288396',
    venue: 'Target Field',
    original_date: '2011/07/23',
    resume_date: '',
    time: '4:10',
    time_date: '2011/07/23 4:10',
    time_date_aw_lg: '2011/07/23 4:10',
    time_date_hm_lg: '2011/07/23 4:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '4:10',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '3:10',
    home_time_zone: 'CT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '4:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '4:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '3312',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '4',
    home_name_abbrev: 'MIN',
    home_code: 'min',
    home_file_code: 'min',
    home_team_id: '142',
    home_team_city: 'Minnesota',
    home_team_name: 'Twins',
    home_division: 'C',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'DET',
    away_code: 'det',
    away_file_code: 'det',
    away_team_id: '116',
    away_team_city: 'Detroit',
    away_team_name: 'Tigers',
    away_division: 'C',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USMN0503',
    location: 'Minneapolis, MN',
    gameday: '2011_07_23_detmlb_minmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '53',
    away_loss: '47',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '47',
    home_loss: '53',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_detmlb_minmlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288393-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_atlmlb_cinmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288393-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288393-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_atlmlb_cinmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_atlmlb_cinmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_atlmlb_cinmlb_1&mode=preview&c_id=mlb',
      tv_station: 'FOX',
    },
    broadcast: {
      home: { tv: 'FOX', radio: 'WLW 700' },
      away: { tv: 'FOX', radio: '680 AM/93.7 FM The Fan, WNNX 100.5' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '2',
      strikes: '0',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {},
    linescore: {
      inning: [
        { home: '1', away: '0' },
        { home: '0', away: '2' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '3', away: '0' },
        { home: '7', away: '0' },
        { home: '0', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '11', away: '2', diff: '9' },
      h: { home: '13', away: '6' },
      e: { home: '1', away: '0' },
      hr: { home: '8', away: '4' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Homer',
      id: '456701',
      last: 'Bailey',
      name_display_roster: 'Bailey',
      number: '34',
      wins: '5',
      losses: '4',
      era: '3.67',
    },
    losing_pitcher: {
      first: 'Derek',
      id: '117955',
      last: 'Lowe',
      name_display_roster: 'Lowe',
      number: '32',
      wins: '6',
      losses: '8',
      era: '4.49',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/atlcin_288393_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/atlcin_288393_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/atlcin_288393_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288393-2011-07-23',
        start: '2011-07-23T20:10:00Z',
        title: 'ATL @ CIN',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/atlcin_288393_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/atlmlb-cinmlb-1',
    game_pk: '288393',
    venue: 'Great American Ball Park',
    original_date: '2011/07/23',
    resume_date: '',
    time: '4:10',
    time_date: '2011/07/23 4:10',
    time_date_aw_lg: '2011/07/23 4:10',
    time_date_hm_lg: '2011/07/23 4:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '4:10',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '4:10',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '4:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '4:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '2602',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'CIN',
    home_code: 'cin',
    home_file_code: 'cin',
    home_team_id: '113',
    home_team_city: 'Cincinnati',
    home_team_name: 'Reds',
    home_division: 'C',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'ATL',
    away_code: 'atl',
    away_file_code: 'atl',
    away_team_id: '144',
    away_team_city: 'Atlanta',
    away_team_name: 'Braves',
    away_division: 'E',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USOH0188',
    location: 'Cincinnati, OH',
    gameday: '2011_07_23_atlmlb_cinmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '59',
    away_loss: '42',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '49',
    home_loss: '51',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_atlmlb_cinmlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288403-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_slnmlb_pitmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288403-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288403-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_slnmlb_pitmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_slnmlb_pitmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_slnmlb_pitmlb_1&mode=preview&c_id=mlb',
      tv_station: 'ROOT SPORTS',
    },
    broadcast: {
      home: { tv: 'ROOT SPORTS', radio: 'WPGB-FM 104.7' },
      away: { tv: 'FS-M', radio: 'KMOX 1120' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Bottom',
      note: '',
      reason: '',
      inning: '9',
      balls: '1',
      strikes: '1',
      outs: '3',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '204020',
          last: 'Berkman',
          first: 'Lance',
          name_display_roster: 'Berkman',
          number: '12',
          hr: '1',
          std_hr: '27',
          inning: '5',
          runners: '2',
          team_code: 'sln',
        },
        {
          id: '425877',
          last: 'Molina',
          first: 'Yadier',
          name_display_roster: 'Molina',
          number: '4',
          hr: '1',
          std_hr: '7',
          inning: '5',
          runners: '0',
          team_code: 'sln',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '0', away: '0' },
        { home: '1', away: '2' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '5' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '2' },
      ],
      r: { home: '1', away: '9', diff: '8' },
      h: { home: '8', away: '12' },
      e: { home: '0', away: '0' },
      hr: { home: '8', away: '6' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Jaime',
      id: '448802',
      last: 'Garcia',
      name_display_roster: 'Garcia',
      number: '54',
      wins: '10',
      losses: '4',
      era: '3.01',
    },
    losing_pitcher: {
      first: 'Kevin',
      id: '429781',
      last: 'Correia',
      name_display_roster: 'Correia',
      number: '29',
      wins: '11',
      losses: '8',
      era: '4.38',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/slnpit_288403_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/slnpit_288403_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/slnpit_288403_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: { type: 'game', calendar_event_id: '14-288403-2011-07-23' },
    },
    id: '2011/07/23/slnmlb-pitmlb-1',
    game_pk: '288403',
    venue: 'PNC Park',
    original_date: '2011/07/23',
    resume_date: '',
    time: '7:05',
    time_date: '2011/07/23 7:05',
    time_date_aw_lg: '2011/07/23 7:05',
    time_date_hm_lg: '2011/07/23 7:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '6:05',
    away_time_zone: 'CT',
    away_ampm: 'PM',
    home_time: '7:05',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '7:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '7:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '31',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'PIT',
    home_code: 'pit',
    home_file_code: 'pit',
    home_team_id: '134',
    home_team_city: 'Pittsburgh',
    home_team_name: 'Pirates',
    home_division: 'C',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'STL',
    away_code: 'sln',
    away_file_code: 'stl',
    away_team_id: '138',
    away_team_city: 'St. Louis',
    away_team_name: 'Cardinals',
    away_division: 'C',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USPA1290',
    location: 'Pittsburgh, PA',
    gameday: '2011_07_23_slnmlb_pitmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '53',
    away_loss: '47',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '51',
    home_loss: '47',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_slnmlb_pitmlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288392-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_anamlb_balmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288392-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288392-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_anamlb_balmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_anamlb_balmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_anamlb_balmlb_1&mode=preview&c_id=mlb',
      tv_station: 'MASN HD',
    },
    broadcast: {
      home: { tv: 'MASN HD', radio: '1090 WBAL' },
      away: { tv: 'FS-W', radio: 'KLAA 830' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '3',
      strikes: '3',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '150484',
          last: 'Wells',
          first: 'Vernon',
          name_display_roster: 'Wells',
          number: '10',
          hr: '1',
          std_hr: '16',
          inning: '1',
          runners: '1',
          team_code: 'ana',
        },
        {
          id: '430945',
          last: 'Jones',
          first: 'Adam',
          name_display_roster: 'Jones',
          number: '10',
          hr: '1',
          std_hr: '17',
          inning: '4',
          runners: '0',
          team_code: 'bal',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '0', away: '2' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '2', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '3', away: '2', diff: '1' },
      h: { home: '13', away: '8' },
      e: { home: '0', away: '0' },
      hr: { home: '9', away: '7' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Brad',
      id: '448269',
      last: 'Bergesen',
      name_display_roster: 'Bergesen',
      number: '35',
      wins: '2',
      losses: '6',
      era: '5.54',
    },
    losing_pitcher: {
      first: 'Joel',
      id: '334492',
      last: 'Pineiro',
      name_display_roster: 'Pineiro',
      number: '35',
      wins: '5',
      losses: '5',
      era: '4.61',
    },
    save_pitcher: {
      first: 'Kevin',
      id: '276514',
      last: 'Gregg',
      name_display_roster: 'Gregg',
      number: '63',
      wins: '0',
      losses: '1',
      era: '3.79',
      saves: '16',
      svo: '20',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/anabal_288392_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/anabal_288392_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/anabal_288392_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: { type: 'game', calendar_event_id: '14-288392-2011-07-23' },
    },
    id: '2011/07/23/anamlb-balmlb-1',
    game_pk: '288392',
    venue: 'Oriole Park at Camden Yards',
    original_date: '2011/07/23',
    resume_date: '',
    time: '7:05',
    time_date: '2011/07/23 7:05',
    time_date_aw_lg: '2011/07/23 7:05',
    time_date_hm_lg: '2011/07/23 7:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '4:05',
    away_time_zone: 'PT',
    away_ampm: 'PM',
    home_time: '7:05',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '7:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '7:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '2',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'BAL',
    home_code: 'bal',
    home_file_code: 'bal',
    home_team_id: '110',
    home_team_city: 'Baltimore',
    home_team_name: 'Orioles',
    home_division: 'E',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'LAA',
    away_code: 'ana',
    away_file_code: 'ana',
    away_team_id: '108',
    away_team_city: 'LA Angels',
    away_team_name: 'Angels',
    away_division: 'W',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USMD0018',
    location: 'Baltimore, MD',
    gameday: '2011_07_23_anamlb_balmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '54',
    away_loss: '47',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '40',
    home_loss: '57',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_anamlb_balmlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288394-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_chamlb_clemlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288394-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288394-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_chamlb_clemlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_chamlb_clemlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_chamlb_clemlb_1&mode=preview&c_id=mlb',
      tv_station: 'STO-HD',
    },
    broadcast: {
      home: { tv: 'STO-HD', radio: 'WTAM 1100' },
      away: { tv: 'WGN', radio: '670 The Score' },
    },
    status: {
      status: 'Postponed',
      ind: 'DR',
      inning_state: '',
      note: '',
      reason: '',
      inning: '',
      balls: '',
      strikes: '',
      outs: '',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {},
    linescore: {
      r: { home: '0', away: '0', diff: '0' },
      h: { home: '', away: '' },
      e: { home: '', away: '' },
      hr: { home: '9', away: '7' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
    },
    losing_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/chacle_288394_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/chacle_288394_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/chacle_288394_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: { type: 'game', calendar_event_id: '14-288394-2011-07-23' },
    },
    id: '2011/07/23/chamlb-clemlb-1',
    game_pk: '288394',
    venue: 'Progressive Field',
    original_date: '2011/07/23',
    resume_date: '',
    time: '7:05',
    time_date: '2011/07/23 7:05',
    time_date_aw_lg: '2011/07/23 7:05',
    time_date_hm_lg: '2011/07/23 7:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '6:05',
    away_time_zone: 'CT',
    away_ampm: 'PM',
    home_time: '7:05',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '7:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '7:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '5',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'CLE',
    home_code: 'cle',
    home_file_code: 'cle',
    home_team_id: '114',
    home_team_city: 'Cleveland',
    home_team_name: 'Indians',
    home_division: 'C',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'CWS',
    away_code: 'cha',
    away_file_code: 'cws',
    away_team_id: '145',
    away_team_city: 'Chi White Sox',
    away_team_name: 'White Sox',
    away_division: 'C',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USOH0195',
    location: 'Cleveland, OH',
    gameday: '2011_07_23_chamlb_clemlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '48',
    away_loss: '51',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '51',
    home_loss: '47',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_chamlb_clemlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288399-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_nynmlb_flomlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288399-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288399-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_nynmlb_flomlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_nynmlb_flomlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_nynmlb_flomlb_1&mode=preview&c_id=mlb',
      tv_station: 'FS-F HD',
    },
    broadcast: {
      home: { tv: 'FS-F HD', radio: 'WAXY 790, WAQI 710' },
      away: { tv: 'WPIX', radio: 'WFAN 660/101.9 FM' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '0',
      strikes: '1',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '489149',
          last: 'Morrison',
          first: 'Logan',
          name_display_roster: 'Morrison',
          number: '20',
          hr: '2',
          std_hr: '14',
          inning: '6',
          runners: '0',
          team_code: 'flo',
        },
        {
          id: '459991',
          last: 'Sanchez',
          first: 'Gaby',
          name_display_roster: 'Sanchez',
          number: '15',
          hr: '2',
          std_hr: '16',
          inning: '7',
          runners: '1',
          team_code: 'flo',
        },
        {
          id: '446263',
          last: 'Duda',
          first: 'Lucas',
          name_display_roster: 'Duda',
          number: '21',
          hr: '2',
          std_hr: '1',
          inning: '9',
          runners: '0',
          team_code: 'nyn',
        },
        {
          id: '408314',
          last: 'Reyes',
          first: 'Jose',
          name_display_roster: 'Reyes',
          number: '7',
          hr: '2',
          std_hr: '4',
          inning: '9',
          runners: '0',
          team_code: 'nyn',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '2' },
        { home: '4', away: '0' },
        { home: '3', away: '1' },
        { home: '1', away: '0' },
        { home: '', away: '2' },
      ],
      r: { home: '8', away: '5', diff: '3' },
      h: { home: '11', away: '9' },
      e: { home: '0', away: '1' },
      hr: { home: '12', away: '9' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Burke',
      id: '488674',
      last: 'Badenhop',
      name_display_roster: 'Badenhop',
      number: '31',
      wins: '2',
      losses: '1',
      era: '4.24',
    },
    losing_pitcher: {
      first: 'Chris',
      id: '425626',
      last: 'Capuano',
      name_display_roster: 'Capuano',
      number: '38',
      wins: '8',
      losses: '10',
      era: '4.26',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/nynflo_288399_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/nynflo_288399_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/nynflo_288399_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288399-2011-07-23',
        start: '2011-07-23T23:10:00Z',
        title: 'NYM @ FLA',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/nynflo_288399_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/nynmlb-flomlb-1',
    game_pk: '288399',
    venue: 'Sun Life Stadium',
    original_date: '2011/07/23',
    resume_date: '',
    time: '7:10',
    time_date: '2011/07/23 7:10',
    time_date_aw_lg: '2011/07/23 7:10',
    time_date_hm_lg: '2011/07/23 7:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '7:10',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '7:10',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '7:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '7:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '20',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '34',
    series_num: '34',
    ser_games: '3',
    home_name_abbrev: 'FLA',
    home_code: 'flo',
    home_file_code: 'fla',
    home_team_id: '146',
    home_team_city: 'Florida',
    home_team_name: 'Marlins',
    home_division: 'E',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'NYM',
    away_code: 'nyn',
    away_file_code: 'nym',
    away_team_id: '121',
    away_team_city: 'NY Mets',
    away_team_name: 'Mets',
    away_division: 'E',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USFL0316',
    location: 'Miami, FL',
    gameday: '2011_07_23_nynmlb_flomlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '50',
    away_loss: '50',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '48',
    home_loss: '53',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_nynmlb_flomlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288402-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_seamlb_bosmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288402-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288402-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_seamlb_bosmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_seamlb_bosmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_seamlb_bosmlb_1&mode=preview&c_id=mlb',
      tv_station: 'NESN',
    },
    broadcast: {
      home: { tv: 'NESN', radio: 'WEEI 850, WUFC 1510' },
      away: { tv: 'ROOT SPORTS', radio: '710 ESPN' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '2',
      strikes: '3',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: {
        id: '455077',
        last: 'Carp',
        first: 'Mike',
        name_display_roster: 'Carp',
        number: '20',
        hr: '1',
        std_hr: '2',
        inning: '7',
        runners: '0',
        team_code: 'sea',
      },
    },
    linescore: {
      inning: [
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '3', away: '1' },
        { home: '0', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '3', away: '1', diff: '2' },
      h: { home: '10', away: '9' },
      e: { home: '0', away: '2' },
      hr: { home: '12', away: '10' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Josh',
      id: '277417',
      last: 'Beckett',
      name_display_roster: 'Beckett',
      number: '19',
      wins: '9',
      losses: '3',
      era: '2.07',
    },
    losing_pitcher: {
      first: 'Blake',
      id: '518444',
      last: 'Beavan',
      name_display_roster: 'Beavan',
      number: '49',
      wins: '1',
      losses: '2',
      era: '3.04',
    },
    save_pitcher: {
      first: 'Jonathan',
      id: '449097',
      last: 'Papelbon',
      name_display_roster: 'Papelbon',
      number: '58',
      wins: '2',
      losses: '0',
      era: '3.67',
      saves: '23',
      svo: '24',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/seabos_288402_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/seabos_288402_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/seabos_288402_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288402-2011-07-23',
        start: '2011-07-23T23:10:00Z',
        title: 'SEA @ BOS',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/seabos_288402_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/seamlb-bosmlb-1',
    game_pk: '288402',
    venue: 'Fenway Park',
    original_date: '2011/07/23',
    resume_date: '',
    time: '7:10',
    time_date: '2011/07/23 7:10',
    time_date_aw_lg: '2011/07/23 7:10',
    time_date_hm_lg: '2011/07/23 7:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '4:10',
    away_time_zone: 'PT',
    away_ampm: 'PM',
    home_time: '7:10',
    home_time_zone: 'ET',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '7:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '7:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '3',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'BOS',
    home_code: 'bos',
    home_file_code: 'bos',
    home_team_id: '111',
    home_team_city: 'Boston',
    home_team_name: 'Red Sox',
    home_division: 'E',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'SEA',
    away_code: 'sea',
    away_file_code: 'sea',
    away_team_id: '136',
    away_team_city: 'Seattle',
    away_team_name: 'Mariners',
    away_division: 'W',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USMA0046',
    location: 'Boston, MA',
    gameday: '2011_07_23_seamlb_bosmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '43',
    away_loss: '57',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '61',
    home_loss: '37',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_seamlb_bosmlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288404-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tbamlb_kcamlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288404-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288404-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tbamlb_kcamlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tbamlb_kcamlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tbamlb_kcamlb_1&mode=preview&c_id=mlb',
      tv_station: 'FSKC',
    },
    broadcast: {
      home: { tv: 'FSKC', radio: 'KCSP 610' },
      away: { tv: 'Sun Sports HD', radio: 'WDAE 620 AM/95.3 FM, WGES 680' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Bottom',
      note: 'None out when winning run scored.',
      reason: '',
      inning: '10',
      balls: '0',
      strikes: '0',
      outs: '0',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {},
    linescore: {
      inning: [
        { home: '0', away: '1' },
        { home: '0', away: '1' },
        { home: '0', away: '0' },
        { home: '2', away: '0' },
        { home: '0', away: '1' },
        { home: '1', away: '1' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '1', away: '0' },
      ],
      r: { home: '5', away: '4', diff: '1' },
      h: { home: '10', away: '11' },
      e: { home: '0', away: '2' },
      hr: { home: '12', away: '10' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Joakim',
      id: '465657',
      last: 'Soria',
      name_display_roster: 'Soria',
      number: '48',
      wins: '5',
      losses: '3',
      era: '3.64',
    },
    losing_pitcher: {
      first: 'Brandon',
      id: '460156',
      last: 'Gomes',
      name_display_roster: 'Gomes',
      number: '47',
      wins: '0',
      losses: '1',
      era: '3.78',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/tbakca_288404_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/tbakca_288404_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/tbakca_288404_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288404-2011-07-23',
        start: '2011-07-23T23:10:00Z',
        title: 'TB @ KC',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/tbakca_288404_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/tbamlb-kcamlb-1',
    game_pk: '288404',
    venue: 'Kauffman Stadium',
    original_date: '2011/07/23',
    resume_date: '',
    time: '7:10',
    time_date: '2011/07/23 7:10',
    time_date_aw_lg: '2011/07/23 7:10',
    time_date_hm_lg: '2011/07/23 7:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '7:10',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '6:10',
    home_time_zone: 'CT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '7:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '7:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '7',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'KC',
    home_code: 'kca',
    home_file_code: 'kc',
    home_team_id: '118',
    home_team_city: 'Kansas City',
    home_team_name: 'Royals',
    home_division: 'C',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'TB',
    away_code: 'tba',
    away_file_code: 'tb',
    away_team_id: '139',
    away_team_city: 'Tampa Bay',
    away_team_name: 'Rays',
    away_division: 'E',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USMO0460',
    location: 'Kansas City, MO',
    gameday: '2011_07_23_tbamlb_kcamlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '52',
    away_loss: '47',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '42',
    home_loss: '58',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_tbamlb_kcamlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288405-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tormlb_texmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288405-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288405-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tormlb_texmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tormlb_texmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_tormlb_texmlb_1&mode=preview&c_id=mlb',
      tv_station: 'FSSW',
    },
    broadcast: {
      home: { tv: 'FSSW', radio: '103.3 ESPN' },
      away: { tv: 'SN', radio: 'SN590' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Bottom',
      note: 'Two out when winning run scored.',
      reason: '',
      inning: '9',
      balls: '1',
      strikes: '2',
      outs: '2',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: {
        id: '450317',
        last: 'Arencibia',
        first: 'J.P.',
        name_display_roster: 'Arencibia',
        number: '9',
        hr: '1',
        std_hr: '15',
        inning: '6',
        runners: '0',
        team_code: 'tor',
      },
    },
    linescore: {
      inning: [
        { home: '0', away: '1' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '1', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '3' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '2', away: '0' },
      ],
      r: { home: '5', away: '4', diff: '1' },
      h: { home: '12', away: '9' },
      e: { home: '1', away: '1' },
      hr: { home: '12', away: '11' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Darren',
      id: '119984',
      last: 'Oliver',
      name_display_roster: 'Oliver',
      number: '28',
      wins: '3',
      losses: '5',
      era: '2.36',
    },
    losing_pitcher: {
      first: 'Marc',
      id: '519240',
      last: 'Rzepczynski',
      name_display_roster: 'Rzepczynski',
      number: '34',
      wins: '2',
      losses: '3',
      era: '2.97',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/tortex_288405_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/tortex_288405_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/tortex_288405_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: { type: 'game', calendar_event_id: '14-288405-2011-07-23' },
    },
    id: '2011/07/23/tormlb-texmlb-1',
    game_pk: '288405',
    venue: 'Rangers Ballpark in Arlington',
    original_date: '2011/07/23',
    resume_date: '',
    time: '8:05',
    time_date: '2011/07/23 8:05',
    time_date_aw_lg: '2011/07/23 8:05',
    time_date_hm_lg: '2011/07/23 8:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '8:05',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '7:05',
    home_time_zone: 'CT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '8:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '8:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '13',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'TEX',
    home_code: 'tex',
    home_file_code: 'tex',
    home_team_id: '140',
    home_team_city: 'Texas',
    home_team_name: 'Rangers',
    home_division: 'W',
    home_league_id: '103',
    home_sport_code: 'mlb',
    away_name_abbrev: 'TOR',
    away_code: 'tor',
    away_file_code: 'tor',
    away_team_id: '141',
    away_team_city: 'Toronto',
    away_team_name: 'Blue Jays',
    away_division: 'E',
    away_league_id: '103',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USTX0045',
    location: 'Arlington, TX',
    gameday: '2011_07_23_tormlb_texmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '50',
    away_loss: '51',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '58',
    home_loss: '43',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_tormlb_texmlb_1',
    inning_break_length: '',
    league: 'AA',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288395-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_colmlb_arimlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288395-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288395-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_colmlb_arimlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_colmlb_arimlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_colmlb_arimlb_1&mode=preview&c_id=mlb',
      tv_station: 'FS-A, MLBN',
    },
    broadcast: {
      home: {
        tv: 'FS-A, MLBN',
        radio: 'ESPN Phoenix 620, ESPN Deportes 710',
      },
      away: { tv: 'ROOT SPORTS, MLBN', radio: 'KOA 850 AM' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '3',
      strikes: '2',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: [
        {
          id: '453064',
          last: 'Tulowitzki',
          first: 'Troy',
          name_display_roster: 'Tulowitzki',
          number: '2',
          hr: '1',
          std_hr: '19',
          inning: '2',
          runners: '0',
          team_code: 'col',
        },
        {
          id: '471083',
          last: 'Montero',
          first: 'Miguel',
          name_display_roster: 'Montero',
          number: '26',
          hr: '1',
          std_hr: '12',
          inning: '2',
          runners: '1',
          team_code: 'ari',
        },
        {
          id: '457708',
          last: 'Upton',
          first: 'Justin',
          name_display_roster: 'Upton',
          number: '10',
          hr: '1',
          std_hr: '17',
          inning: '7',
          runners: '3',
          team_code: 'ari',
        },
      ],
    },
    linescore: {
      inning: [
        { home: '5', away: '0' },
        { home: '2', away: '1' },
        { home: '0', away: '0' },
        { home: '0', away: '2' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '4', away: '0' },
        { home: '0', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '12', away: '3', diff: '9' },
      h: { home: '14', away: '7' },
      e: { home: '0', away: '1' },
      hr: { home: '14', away: '12' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Josh',
      id: '518567',
      last: 'Collmenter',
      name_display_roster: 'Collmenter',
      number: '55',
      wins: '6',
      losses: '5',
      era: '2.74',
    },
    losing_pitcher: {
      first: 'Jason',
      id: '434628',
      last: 'Hammel',
      name_display_roster: 'Hammel',
      number: '46',
      wins: '5',
      losses: '10',
      era: '4.75',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/colari_288395_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/colari_288395_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/colari_288395_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: { type: 'game', calendar_event_id: '14-288395-2011-07-23' },
    },
    id: '2011/07/23/colmlb-arimlb-1',
    game_pk: '288395',
    venue: 'Chase Field',
    original_date: '2011/07/23',
    resume_date: '',
    time: '8:10',
    time_date: '2011/07/23 8:10',
    time_date_aw_lg: '2011/07/23 8:10',
    time_date_hm_lg: '2011/07/23 8:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '6:10',
    away_time_zone: 'MT',
    away_ampm: 'PM',
    home_time: '5:10',
    home_time_zone: 'MST',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '8:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '8:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '15',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'ARI',
    home_code: 'ari',
    home_file_code: 'ari',
    home_team_id: '109',
    home_team_city: 'Arizona',
    home_team_name: 'D-backs',
    home_division: 'W',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'COL',
    away_code: 'col',
    away_file_code: 'col',
    away_team_id: '115',
    away_team_city: 'Colorado',
    away_team_name: 'Rockies',
    away_division: 'W',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USAZ0166',
    location: 'Phoenix, AZ',
    gameday: '2011_07_23_colmlb_arimlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '48',
    away_loss: '53',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '54',
    home_loss: '47',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_colmlb_arimlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288398-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_milmlb_sfnmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288398-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288398-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_milmlb_sfnmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_milmlb_sfnmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_milmlb_sfnmlb_1&mode=preview&c_id=mlb',
      tv_station: 'CSBA HD, MLBN',
    },
    broadcast: {
      home: { tv: 'CSBA HD, MLBN', radio: 'KNBR 680, KIQI 1010, KATD 990' },
      away: { tv: 'FSN, MLBN', radio: 'WTMJ 620' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Top',
      note: '',
      reason: '',
      inning: '9',
      balls: '0',
      strikes: '1',
      outs: '3',
      top_inning: 'Y',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {
      player: {
        id: '460075',
        last: 'Braun',
        first: 'Ryan',
        name_display_roster: 'Braun',
        number: '8',
        hr: '1',
        std_hr: '19',
        inning: '4',
        runners: '0',
        team_code: 'mil',
      },
    },
    linescore: {
      inning: [
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '2', away: '1' },
        { home: '1', away: '1' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '', away: '0' },
      ],
      r: { home: '4', away: '2', diff: '2' },
      h: { home: '10', away: '7' },
      e: { home: '0', away: '0' },
      hr: { home: '14', away: '13' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Ryan',
      id: '285064',
      last: 'Vogelsong',
      name_display_roster: 'Vogelsong',
      number: '32',
      wins: '8',
      losses: '1',
      era: '2.10',
    },
    losing_pitcher: {
      first: 'Randy',
      id: '150116',
      last: 'Wolf',
      name_display_roster: 'Wolf',
      number: '43',
      wins: '6',
      losses: '8',
      era: '3.62',
    },
    save_pitcher: {
      first: 'Brian',
      id: '451216',
      last: 'Wilson',
      name_display_roster: 'Wilson',
      number: '38',
      wins: '6',
      losses: '2',
      era: '2.89',
      saves: '30',
      svo: '34',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/milsfn_288398_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/milsfn_288398_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/milsfn_288398_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288398-2011-07-23',
        start: '2011-07-24T01:05:00Z',
        title: 'MIL @ SF',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/milsfn_288398_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_archive',
      },
    },
    id: '2011/07/23/milmlb-sfnmlb-1',
    game_pk: '288398',
    venue: 'AT&T Park',
    original_date: '2011/07/23',
    resume_date: '',
    time: '9:05',
    time_date: '2011/07/23 9:05',
    time_date_aw_lg: '2011/07/23 9:05',
    time_date_hm_lg: '2011/07/23 9:05',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '8:05',
    away_time_zone: 'CT',
    away_ampm: 'PM',
    home_time: '6:05',
    home_time_zone: 'PT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '9:05',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '9:05',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '2395',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'SF',
    home_code: 'sfn',
    home_file_code: 'sf',
    home_team_id: '137',
    home_team_city: 'San Francisco',
    home_team_name: 'Giants',
    home_division: 'W',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'MIL',
    away_code: 'mil',
    away_file_code: 'mil',
    away_team_id: '158',
    away_team_city: 'Milwaukee',
    away_team_name: 'Brewers',
    away_division: 'C',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USCA0987',
    location: 'San Francisco, CA',
    gameday: '2011_07_23_milmlb_sfnmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '54',
    away_loss: '48',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '58',
    home_loss: '43',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_milmlb_sfnmlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288406-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288406-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288406-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=preview&c_id=mlb',
      tv_station: 'PRIME, TWC 858',
    },
    broadcast: {
      home: { tv: 'PRIME, TWC 858', radio: 'KABC 790, KTNQ 1020' },
      away: { tv: 'MASN 2 HD', radio: '106.7 The Fan, WFED 1500' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Bottom',
      note: 'One out when winning run scored.',
      reason: '',
      inning: '9',
      balls: '2',
      strikes: '0',
      outs: '1',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {},
    linescore: {
      inning: [
        { home: '1', away: '3' },
        { home: '1', away: '0' },
        { home: '3', away: '3' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
      ],
      r: { home: '7', away: '6', diff: '1' },
      h: { home: '14', away: '9' },
      e: { home: '0', away: '1' },
      hr: { home: '14', away: '13' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Javy',
      id: '457915',
      last: 'Guerra',
      name_display_roster: 'Guerra',
      number: '54',
      wins: '2',
      losses: '0',
      era: '2.08',
    },
    losing_pitcher: {
      first: 'Ryan',
      id: '458919',
      last: 'Mattheus',
      name_display_roster: 'Mattheus',
      number: '52',
      wins: '2',
      losses: '2',
      era: '1.89',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288406-2011-07-23',
        start: '2011-07-24T02:10:00Z',
        title: 'WSH @ LAD',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/wasmlb-lanmlb-1',
    game_pk: '288406',
    venue: 'Dodger Stadium',
    original_date: '2011/07/23',
    resume_date: '',
    time: '10:10',
    time_date: '2011/07/23 10:10',
    time_date_aw_lg: '2011/07/23 10:10',
    time_date_hm_lg: '2011/07/23 10:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '10:10',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '7:10',
    home_time_zone: 'PT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '10:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '10:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '22',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'LAD',
    home_code: 'lan',
    home_file_code: 'la',
    home_team_id: '119',
    home_team_city: 'LA Dodgers',
    home_team_name: 'Dodgers',
    home_division: 'W',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'WSH',
    away_code: 'was',
    away_file_code: 'was',
    away_team_id: '120',
    away_team_city: 'Washington',
    away_team_name: 'Nationals',
    away_division: 'E',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USCA0638',
    location: 'Los Angeles, CA',
    gameday: '2011_07_23_wasmlb_lanmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '49',
    away_loss: '51',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '44',
    home_loss: '56',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_wasmlb_lanmlb_1',
    inning_break_length: '',
    league: 'NN',
  },
  {
    links: {
      mlbtv:
        "bam.media.launchPlayer({calendar_event_id:'14-288406-2011-07-23',media_type:'video'})",
      wrapup:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=wrap&c_id=mlb',
      home_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288406-2011-07-23',media_type:'audio'})",
      away_audio:
        "bam.media.launchPlayer({calendar_event_id:'14-288406-2011-07-23',media_type:'audio'})",
      home_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=preview&c_id=mlb',
      away_preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=preview&c_id=mlb',
      preview:
        '/mlb/gameday/index.jsp?gid=2011_07_23_wasmlb_lanmlb_1&mode=preview&c_id=mlb',
      tv_station: 'PRIME, TWC 858',
    },
    broadcast: {
      home: { tv: 'PRIME, TWC 858', radio: 'KABC 790, KTNQ 1020' },
      away: { tv: 'MASN 2 HD', radio: '106.7 The Fan, WFED 1500' },
    },
    status: {
      status: 'Final',
      ind: 'F',
      inning_state: 'Bottom',
      note: 'One out when winning run scored.',
      reason: '',
      inning: '9',
      balls: '2',
      strikes: '0',
      outs: '1',
      top_inning: 'N',
      is_perfect_game: 'N',
      is_no_hitter: 'N',
    },
    home_runs: {},
    linescore: {
      inning: [
        { home: '1', away: '3' },
        { home: '1', away: '0' },
        { home: '3', away: '3' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
        { home: '0', away: '0' },
        { home: '1', away: '0' },
      ],
      r: { home: '7', away: '6', diff: '1' },
      h: { home: '14', away: '9' },
      e: { home: '0', away: '1' },
      hr: { home: '14', away: '13' },
      sb: { home: '0', away: '0' },
      so: { home: '0', away: '0' },
    },
    winning_pitcher: {
      first: 'Javy',
      id: '457915',
      last: 'Guerra',
      name_display_roster: 'Guerra',
      number: '54',
      wins: '2',
      losses: '0',
      era: '2.08',
    },
    losing_pitcher: {
      first: 'Ryan',
      id: '458919',
      last: 'Mattheus',
      name_display_roster: 'Mattheus',
      number: '52',
      wins: '2',
      losses: '2',
      era: '1.89',
    },
    save_pitcher: {
      first: '',
      id: '',
      last: '',
      name_display_roster: '',
      number: '',
      wins: '',
      losses: '',
      era: '',
      saves: '',
      svo: '',
    },
    video_thumbnail:
      'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_7_preview.jpg',
    video_thumbnails: {
      thumbnail: [
        {
          scenario: '7',
          width: '124',
          height: '70',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_7_preview.jpg',
        },
        {
          scenario: '37',
          width: '160',
          height: '90',
          text:
            'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_37_preview.jpg',
        },
      ],
    },
    game_media: {
      media: {
        type: 'game',
        calendar_event_id: '14-288406-2011-07-23',
        start: '2011-07-24T02:10:00Z',
        title: 'WSH @ LAD',
        has_mlbtv: 'true',
        has_milbtv: 'false',
        thumbnail:
          'http://mediadownloads.mlb.com/mlbam/preview/waslan_288406_th_7_preview.jpg',
        free: 'NO',
        enhanced: 'N',
        media_state: 'media_dead',
      },
    },
    id: '2011/07/23/wasmlb-lanmlb-1',
    game_pk: '288406',
    venue: 'Dodger Stadium',
    original_date: '2011/07/23',
    resume_date: '',
    time: '10:10',
    time_date: '2011/07/23 10:10',
    time_date_aw_lg: '2011/07/23 10:10',
    time_date_hm_lg: '2011/07/23 10:10',
    time_zone: 'ET',
    ampm: 'PM',
    first_pitch_et: '',
    away_time: '10:10',
    away_time_zone: 'ET',
    away_ampm: 'PM',
    home_time: '7:10',
    home_time_zone: 'PT',
    home_ampm: 'PM',
    game_type: 'R',
    tiebreaker_sw: 'N',
    time_zone_aw_lg: '-4',
    time_zone_hm_lg: '-4',
    time_aw_lg: '10:10',
    aw_lg_ampm: 'PM',
    tz_aw_lg_gen: 'ET',
    time_hm_lg: '10:10',
    hm_lg_ampm: 'PM',
    tz_hm_lg_gen: 'ET',
    venue_id: '22',
    stats_season: '2011',
    scheduled_innings: '9',
    description: '',
    series: 'Regular Season',
    ser_home_nbr: '33',
    series_num: '33',
    ser_games: '3',
    home_name_abbrev: 'LAD',
    home_code: 'lan',
    home_file_code: 'la',
    home_team_id: '119',
    home_team_city: 'LA Dodgers',
    home_team_name: 'Dodgers',
    home_division: 'W',
    home_league_id: '104',
    home_sport_code: 'mlb',
    away_name_abbrev: 'WSH',
    away_code: 'was',
    away_file_code: 'was',
    away_team_id: '120',
    away_team_city: 'Washington',
    away_team_name: 'Nationals',
    away_division: 'E',
    away_league_id: '104',
    away_sport_code: 'mlb',
    day: 'SAT',
    gameday_sw: 'P',
    double_header_sw: 'N',
    game_nbr: '1',
    tbd_flag: 'N',
    venue_w_chan_loc: 'USCA0638',
    location: 'Los Angeles, CA',
    gameday: '2011_07_23_wasmlb_lanmlb_1',
    away_games_back: '',
    away_games_back_wildcard: '',
    away_win: '49',
    away_loss: '51',
    home_games_back: '',
    home_games_back_wildcard: '',
    home_win: '44',
    home_loss: '56',
    game_data_directory:
      '/components/game/mlb/year_2011/month_07/day_23/gid_2011_07_23_wasmlb_lanmlb_1',
    inning_break_length: '',
    league: 'NN',
  },
];

export default mlbGamesTestData;
